#############################################################################
# Makefile for building: wm3000id
# Generated by qmake (1.07a) (Qt 3.3.4) on: Tue Feb 14 10:43:22 2012
# Project:  wm3000id.pro
# Template: app
# Command: $(QMAKE) -o Makefile wm3000id.pro
#############################################################################

####### Compiler, tools and options

CC       = arm-linux-gcc
CXX      = arm-linux-g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -mcpu=xscale -Wall -W -O2 -g  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -mcpu=xscale -Wall -W -O2 -g  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/mnt/xscale/sources/qt/mkspecs/default -I. -I$(QTDIR)/include -I.ui/ -I.moc/
LINK     = arm-linux-g++
LFLAGS   = -nodefaultlibs -Wl,-rpath-link,/mnt/xscale/sources/xfree86/xc/exports/lib  -Wl,-rpath,$(QTDIR)/lib
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/mnt/xscale/sources/xfree86/xc/exports/lib -lqt-mt -lXext -lX11 -lm
AR       = arm-linux-ar cqs
RANLIB   = 
MOC      = /usr/bin/moc
UIC      = /usr/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = cmdinterpret.h \
		crcutils.h \
		gaussmatrix.h \
		i2ceeprom.h \
		i2cutils.h \
		intelhexfileio.h \
		justdata.h \
		parse.h \
		scpi.h \
		wm3000id.h \
		wmiglobal.h \
		wmjustdata.h \
		wmscpi.h \
		zeraglobal.h \
		zhserver.h
SOURCES = cmdinterpret.cpp \
		cmds.cpp \
		crcutils.cpp \
		gaussmatrix.cpp \
		i2ceeprom.cpp \
		i2cutils.cpp \
		intelhexfileio.cpp \
		justdata.cpp \
		main.cpp \
		parse.cpp \
		scpi.cpp \
		wm3000id.cpp \
		wmjustdata.cpp \
		zhserver.cpp
OBJECTS = .obj/cmdinterpret.o \
		.obj/cmds.o \
		.obj/crcutils.o \
		.obj/gaussmatrix.o \
		.obj/i2ceeprom.o \
		.obj/i2cutils.o \
		.obj/intelhexfileio.o \
		.obj/justdata.o \
		.obj/main.o \
		.obj/parse.o \
		.obj/scpi.o \
		.obj/wm3000id.o \
		.obj/wmjustdata.o \
		.obj/zhserver.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = wm3000id.pro
QMAKE_TARGET = wm3000id
DESTDIR  = 
TARGET   = wm3000id

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: wm3000id.pro  /mnt/xscale/sources/qt/mkspecs/default/qmake.conf /mnt/xscale/sources/qt/lib/libqt-mt.prl
	$(QMAKE) -o Makefile wm3000id.pro
qmake: 
	@$(QMAKE) -o Makefile wm3000id.pro

dist: 
	@mkdir -p .obj/wm3000id && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/wm3000id/ && ( cd `dirname .obj/wm3000id` && $(TAR) wm3000id.tar wm3000id && $(GZIP) wm3000id.tar ) && $(MOVE) `dirname .obj/wm3000id`/wm3000id.tar.gz . && $(DEL_FILE) -r .obj/wm3000id

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/cmdinterpret.o: cmdinterpret.cpp cmdinterpret.h \
		scpi.h \
		zeraglobal.h \
		wmscpi.h \
		parse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cmdinterpret.o cmdinterpret.cpp

.obj/cmds.o: cmds.cpp scpi.h \
		wmscpi.h \
		zhserver.h \
		wm3000id.h \
		cmdinterpret.h \
		parse.h \
		wmjustdata.h \
		justdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cmds.o cmds.cpp

.obj/crcutils.o: crcutils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/crcutils.o crcutils.cpp

.obj/gaussmatrix.o: gaussmatrix.cpp gaussmatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/gaussmatrix.o gaussmatrix.cpp

.obj/i2ceeprom.o: i2ceeprom.cpp i2cutils.h \
		i2ceeprom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/i2ceeprom.o i2ceeprom.cpp

.obj/i2cutils.o: i2cutils.cpp i2cutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/i2cutils.o i2cutils.cpp

.obj/intelhexfileio.o: intelhexfileio.cpp intelhexfileio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/intelhexfileio.o intelhexfileio.cpp

.obj/justdata.o: justdata.cpp justdata.h \
		gaussmatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/justdata.o justdata.cpp

.obj/main.o: main.cpp wmiglobal.h \
		wm3000id.h \
		wmjustdata.h \
		zhserver.h \
		wmscpi.h \
		justdata.h \
		scpi.h \
		parse.h \
		cmdinterpret.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/parse.o: parse.cpp parse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/parse.o parse.cpp

.obj/scpi.o: scpi.cpp scpi.h \
		parse.h \
		wmscpi.h \
		cmdinterpret.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/scpi.o scpi.cpp

.obj/wm3000id.o: wm3000id.cpp zeraglobal.h \
		wmiglobal.h \
		wmjustdata.h \
		cmdinterpret.h \
		zhserver.h \
		wm3000id.h \
		i2ceeprom.h \
		crcutils.h \
		i2cutils.h \
		intelhexfileio.h \
		justdata.h \
		scpi.h \
		wmscpi.h \
		parse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/wm3000id.o wm3000id.cpp

.obj/wmjustdata.o: wmjustdata.cpp wmjustdata.h \
		justdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/wmjustdata.o wmjustdata.cpp

.obj/zhserver.o: zhserver.cpp wmiglobal.h \
		zhserver.h \
		wmscpi.h \
		scpi.h \
		parse.h \
		cmdinterpret.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/zhserver.o zhserver.cpp

####### Install

install:  

uninstall:  

